[package]
name = "tol"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.57", features = ["derive"] }
logos = "0.16.1"
miette = { version = "7.6.0", features = ["fancy"] }
thiserror = "2.0.18"
